name: Testing in Sage

on: [pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 
      image: sagemath/sagemath:latest
      options: --user root
    steps:
    - uses: actions/checkout@v1
    - name: Installing git and dependencies
      run: |
        apt-get -qq update \
        && apt-get -qq install -y --no-install-recommends git apt-transport-https ca-certificates \
        && apt-get -qq clean
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Running sage tests
      run: |
        sage -t ajpastor
